### PR TITLE
Clarify how to install carting using brew

### PR DESCRIPTION
**Pull request by acecilia**

### CODE REVIEW

**Comment by artemnovichkov** [comment]
Hi, @acecilia! Thank for the pull request! May I ask, is it not enough to execute `brew install artemnovichkov/projects/carting`?

**Comment by acecilia** [comment]
Hey :) 
No, it is not enough. I just tried, and got the following error:

```
$ brew install artemnovichkov/projects/carting
Error: No available formula with the name "artemnovichkov/projects/carting" 
Please tap it and then try again: brew tap artemnovichkov/projects
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
```

I managed to install it after tap, as I updated in the readme.

**Comment by artemnovichkov** [comment]
Thanks for the clarification! I guess we can simplify it:
```bash
$ brew tap artemnovichkov/projects
$ brew install carting
```
According to this example: https://github.com/mono0926/LicensePlist#installation

**Comment by artemnovichkov** [comment]
Perfect! Thanks!

**Pull request merged**
